version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5132:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - task-management-network
    environment:
      - ConnectionStrings__DefaultConnection=server=db;port=3306;database=task_management_schema;user=root;password=task_management_password
      - ASPNETCORE_ENVIRONMENT=Development

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: task_management_password
      MYSQL_DATABASE: task_management_schema
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - task-management-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  mysql-data:

networks:
  task-management-network:
